### ISSUE TITLE
Text language

### ISSUE THREAD

**Issue by Helias** [pashok6798/Crash-Bandicoot-NSAMETRIOLOGY-Tool#4]
Could you translate all the russian text in english?

Anyway thanks for your work.

**Comment by pashok6798** [comment]
Oh. I'm sorry, I see your message today only. I'll try to do something. Thanks for patience.

**Comment by pashok6798** [comment]
> Could you translate all the russian text in english?
> 
> Anyway thanks for your work.

I've just updated tool and source codes. Now you can try new version. I'll close your issue.

**Comment by Helias** [comment]
Thank you a lot!

Now I'm trying to compile/run this project on Linux, unfortunately I don't use C# and compiling I get some errors compiling with xbuild on Ubuntu 18.04.1 LTS

> 
> Build FAILED.
> Errors:
> 
> Crash-Bandicoot-NSAMETRIOLOGY-Tool/CBNSTT/CBNSTT.csproj (default targets) ->
> /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GenerateResources target) ->
> 
> 	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> Position: Line 1975, Column 5.
> Inner exception: No valid icon entry were found.
> 
> 	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> Position: Line 1975, Column 5.
> Inner exception: No valid icon entry were found.
> 
> 	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> Position: Line 1975, Column 5.
> Inner exception: No valid icon entry were found.
> 
> 	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> Position: Line 1975, Column 5.
> Inner exception: No valid icon entry were found.
> 
> 	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> Position: Line 1975, Column 5.
> Inner exception: No valid icon entry were found.
> 
> 	 0 Warning(s)
> 	 5 Error(s)
> 

anyway, I will try to solve by myself, thanks for your job

**Comment by pashok6798** [comment]
> Thank you a lot!
> 
> Now I'm trying to compile/run this project on Linux, unfortunately I don't use C# and compiling I get some errors compiling with xbuild on Ubuntu 18.04.1 LTS
> 
> > Build FAILED.
> > Errors:
> > Crash-Bandicoot-NSAMETRIOLOGY-Tool/CBNSTT/CBNSTT.csproj (default targets) ->
> > /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GenerateResources target) ->
> > /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> > Position: Line 1975, Column 5.
> > Inner exception: No valid icon entry were found.
> > /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> > Position: Line 1975, Column 5.
> > Inner exception: No valid icon entry were found.
> > /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> > Position: Line 1975, Column 5.
> > Inner exception: No valid icon entry were found.
> > /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> > Position: Line 1975, Column 5.
> > Inner exception: No valid icon entry were found.
> > /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
> > Position: Line 1975, Column 5.
> > Inner exception: No valid icon entry were found.
> > 0 Warning(s)
> > 5 Error(s)
> 
> anyway, I will try to solve by myself, thanks for your job

Hi. I found out problem with compilation. I've updated src codes and it compiles with MonoDevelop 4.5.1 framework. You can try compile yourself or you can try compiled version (see "Releases").

**Comment by Helias** [comment]
Thanks! I'll try!
