### ISSUE TITLE
Directory Path invalid?

### ISSUE THREAD

**Issue by Helias** [pashok6798/Crash-Bandicoot-NSAMETRIOLOGY-Tool#7]
I just tested the tool and it compile on Linux (Ubuntu 18.04) but when I go to Sound and click "Import Sound" I get this error:

> 
> System.IO.IOException: The directory name is invalid.
>   at System.IO.Directory.ValidateDirectoryListing (System.String path, System.String searchPattern, System.Boolean& stop) [0x00056] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, System.IO.FileAttributes mask, System.IO.FileAttributes attrs) [0x00023] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.IO.DirectoryInfo.GetFiles (System.String searchPattern) [0x00011] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) [0x00002] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.IO.DirectoryInfo.GetFiles (System.String searchPattern, System.IO.SearchOption searchOption) [0x00020] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo:GetFiles (string,System.IO.SearchOption)
>   at CBNSTT.SoundToolForm.button2_Click (System.Object sender, System.EventArgs e) [0x0003d] in <37ba48ab251349eab969de926952e43f>:0 
>   at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x0001c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00024] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.ButtonBase.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x00081] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x0007e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x0016f] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x0004e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x0008e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 

I think that the directory path is invalid but I don't understand why, I tried to debug and fix but I never used C#.

If I print the variable ffd.SelectedPath in function button2_Click (file: SoundToolForm.cs) I get this path (that it's correct):

> /mnt/40BB318407E8AC2E/Giochi/CrashBandicoot/Crash-Bandicoot-NSAMETRIOLOGY-Tool/CBNSTT/bin/Debug/CHAMP_MonkeyBars_bank.igz

**Comment by pashok6798** [comment]
Did you check "\\" in source code? I used it for Windows version.

**Comment by pashok6798** [comment]
Can you build current sources in linux?
